import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const destinationsPath = path.resolve(__dirname, '../src/data/destinations.json');

// Read existing data
const existingData = JSON.parse(fs.readFileSync(destinationsPath, 'utf-8'));
console.log(`Loaded ${existingData.length} existing items.`);

// Filter out any previous kerala additions if re-run, keeping Goa, Munnar, Pondicherry
const baseData = existingData.filter(
  (item) => ['goa', 'munnar', 'pondicherry'].includes(item.destination.toLowerCase())
);
console.log(`Preserved ${baseData.length} core items (Goa, Munnar, Pondicherry).`);

// Helper to calculate realistic sentiment from rating
function makeSentiment(rating, offset = 0) {
  // 4.8 -> ~0.94, 4.4 -> ~0.84, 4.0 -> ~0.75
  const base = 0.5 + (rating - 3.0) * 0.22;
  return Number(Math.max(0.5, Math.min(0.98, base + offset)).toFixed(2));
}

// City definitions with specific themes and attractions
const newCitiesData = [
  // 1. ALLEPPEY (Alappuzha) - Backwaters, Houseboats, Beaches
  {
    city: 'Alleppey',
    places: [
      {
        name: 'Alappuzha Backwaters & Houseboat Cruise',
        category: 'place',
        rating: 4.8,
        reviewCount: 14500,
        sentimentScore: 0.94,
        recentSentimentScore: 0.95,
        recentReviewTrend: 'rising',
        positiveTags: ['Serene canal navigation', 'Authentic floating stay', 'Lush paddy scenery'],
        negativeTags: ['Motorboat engine noise during peak hours', 'Diesel fumes at boarding dock'],
        crowdLevel: 'medium',
        priceTier: 'luxury',
        estimatedCostINR: 3500,
        distanceMinutes: 12,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Punnamada Jetty',
        description: 'Iconic Kerala backwater cruise through tranquil palm-fringed lagoons, emerald paddy fields, and coir hamlets.'
      },
      {
        name: 'Marari Beach & Secluded Palm Grove',
        category: 'place',
        rating: 4.6,
        reviewCount: 4200,
        sentimentScore: 0.89,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'rising',
        positiveTags: ['Golden uncrowded sand', 'Fishing boats at sunrise', 'Pristine coastal breeze'],
        negativeTags: ['Strong undercurrents restrict swimming', 'Limited commercial beach shacks'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 100,
        distanceMinutes: 28,
        interests: ['beaches', 'peaceful spots', 'nature'],
        bestTimeOfDay: 'evening',
        locationZone: 'Mararikulam Coast',
        description: 'A tranquil fishing village beach north of Alleppey known for swaying coconut groves and serene Arabian Sea sunsets.'
      },
      {
        name: 'Alappuzha Lighthouse & Historic Pier',
        category: 'place',
        rating: 4.3,
        reviewCount: 6800,
        sentimentScore: 0.81,
        recentSentimentScore: 0.58,
        recentReviewTrend: 'falling',
        positiveTags: ['Panoramic maritime views', 'Colonial 1862 spiral staircase', 'Cool coastal breeze'],
        negativeTags: ['Steep narrow stair climb congestion', 'Litter along old pier remains', 'Limited parking space'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 50,
        distanceMinutes: 8,
        interests: ['culture', 'beaches'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Beach Promenade',
        description: 'Historic red-and-white striped beacon built in 1862 providing 360-degree vistas of the ancient sea port.'
      },
      {
        name: 'Punnamada Lake & Nehru Trophy Race Track',
        category: 'place',
        rating: 4.7,
        reviewCount: 5100,
        sentimentScore: 0.91,
        recentSentimentScore: 0.92,
        recentReviewTrend: 'stable',
        positiveTags: ['Epicentre of Vallam Kali snake boat races', 'Expansive lake horizon', 'Kayaking trails'],
        negativeTags: ['Extreme festival rush during race weekends', 'Hot midday sun'],
        crowdLevel: 'medium',
        priceTier: 'budget',
        estimatedCostINR: 250,
        distanceMinutes: 10,
        interests: ['culture', 'nature', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Punnamada Basin',
        description: 'Sprawling backwater lake that hosts the world-famous Nehru Trophy snake boat race with 100-oared chundan vallams.'
      }
    ],
    hotels: [
      {
        name: 'Lake Palace Resort Backwater Pavilion',
        category: 'hotel',
        rating: 4.7,
        reviewCount: 2300,
        sentimentScore: 0.92,
        recentSentimentScore: 0.93,
        recentReviewTrend: 'stable',
        positiveTags: ['Private island setting', 'Ayurvedic luxury spa', 'Traditional Kerala architecture'],
        negativeTags: ['Access only via water taxi', 'Premium resort tariff'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 7500,
        distanceMinutes: 20,
        interests: ['peaceful spots', 'nature'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Vembanad Lakefront',
        description: 'Heritage island resort encircled by lotus ponds and backwaters offering ultra-refined tranquil stays.'
      },
      {
        name: 'Venice Premium Heritage Canal Villa',
        category: 'hotel',
        rating: 4.4,
        reviewCount: 1650,
        sentimentScore: 0.85,
        recentSentimentScore: 0.86,
        recentReviewTrend: 'stable',
        positiveTags: ['Affordable canal view rooms', 'Helpful hosts', 'Fresh Kerala breakfast'],
        negativeTags: ['Mosquitoes in canal proximity', 'Narrow approach street'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 2800,
        distanceMinutes: 5,
        interests: ['culture', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Town Canal Side',
        description: 'Charming restored wooden villa beside Alleppey town canals with quick access to boat boarding docks.'
      }
    ],
    restaurants: [
      {
        name: 'Thaff Delicacy Kerala Seafood',
        category: 'restaurant',
        rating: 4.5,
        reviewCount: 3800,
        sentimentScore: 0.88,
        recentSentimentScore: 0.89,
        recentReviewTrend: 'rising',
        positiveTags: ['Karimeen pollichathu perfection', 'Fluffy appams with fish molee', 'Quick table turnaround'],
        negativeTags: ['Busy lunch crowd', 'Basic seating decor'],
        crowdLevel: 'high',
        priceTier: 'moderate',
        estimatedCostINR: 650,
        distanceMinutes: 6,
        interests: ['food'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Central Town',
        description: 'Renowned culinary landmark in Alleppey celebrated for fiery pearl spot fish fry and Travancore seafood delights.'
      },
      {
        name: 'Cassia Canal View Cafe & Bakery',
        category: 'restaurant',
        rating: 4.4,
        reviewCount: 1200,
        sentimentScore: 0.86,
        recentSentimentScore: 0.88,
        recentReviewTrend: 'stable',
        positiveTags: ['Fresh brewed coffee & wood-fired pizza', 'Serene canal deck view', 'Air conditioned lounge'],
        negativeTags: ['Slightly slower cafe service', 'Limited parking'],
        crowdLevel: 'low',
        priceTier: 'moderate',
        estimatedCostINR: 500,
        distanceMinutes: 8,
        interests: ['food', 'peaceful spots'],
        bestTimeOfDay: 'evening',
        locationZone: 'Canal Road',
        description: 'Relaxed waterfront cafe offering artisanal sourdough, Italian pizzas, and aromatic Nilgiri coffee brews.'
      }
    ]
  },

  // 2. KOCHI (Cochin) - Historic Port, Fort Kochi, Kathakali, Spice Heritage
  {
    city: 'Kochi',
    places: [
      {
        name: 'Fort Kochi Chinese Fishing Nets & Walkway',
        category: 'place',
        rating: 4.6,
        reviewCount: 22000,
        sentimentScore: 0.89,
        recentSentimentScore: 0.90,
        recentReviewTrend: 'stable',
        positiveTags: ['Cantilevered 14th-century fishing nets', 'Glorious Arabian sunset', 'Breezy colonial seaside'],
        negativeTags: ['Aggressive souvenir hawkers', 'Occasional debris along water edge'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 50,
        distanceMinutes: 15,
        interests: ['culture', 'beaches', 'peaceful spots'],
        bestTimeOfDay: 'evening',
        locationZone: 'Fort Kochi Pier',
        description: 'Iconic cantilevered shore nets introduced by Chinese traders in the 14th century, framing Kochi’s world-famous sunset.'
      },
      {
        name: 'Mattancherry Palace & Jew Town Heritage Walk',
        category: 'place',
        rating: 4.7,
        reviewCount: 16500,
        sentimentScore: 0.91,
        recentSentimentScore: 0.93,
        recentReviewTrend: 'rising',
        positiveTags: ['Exquisite Ramayana murals', 'Ancient antique and spice stores', '1568 Paradesi Synagogue'],
        negativeTags: ['No photography inside palace mural rooms', 'Crowded narrow alleys'],
        crowdLevel: 'medium',
        priceTier: 'budget',
        estimatedCostINR: 40,
        distanceMinutes: 20,
        interests: ['culture', 'food'],
        bestTimeOfDay: 'morning',
        locationZone: 'Mattancherry',
        description: 'Dutch-Portuguese royal palace featuring priceless mythological tempera murals and antique trade alleys.'
      },
      {
        name: 'Kerala Kathakali Centre Classical Performance',
        category: 'place',
        rating: 4.8,
        reviewCount: 5900,
        sentimentScore: 0.94,
        recentSentimentScore: 0.96,
        recentReviewTrend: 'rising',
        positiveTags: ['Intricate pre-show face makeup viewing', 'Spellbinding facial expressions & mudras', 'Intimate stage acoustics'],
        negativeTags: ['Requires advance ticket reservation', 'Traditional wooden benches'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 500,
        distanceMinutes: 14,
        interests: ['culture', 'nightlife'],
        bestTimeOfDay: 'night',
        locationZone: 'Fort Kochi Central',
        description: 'Authentic performing arts auditorium where master artists demonstrate the elaborate makeup and mudras of Kathakali.'
      },
      {
        name: 'Marine Drive Waterfront Promenade & Rainbow Bridge',
        category: 'place',
        rating: 4.4,
        reviewCount: 18000,
        sentimentScore: 0.84,
        recentSentimentScore: 0.85,
        recentReviewTrend: 'stable',
        positiveTags: ['Breezy evening strolls', 'Sunset harbor cruises', 'Illuminated rainbow arch bridge'],
        negativeTags: ['High evening foot traffic', 'Limited shaded seating'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 150,
        distanceMinutes: 5,
        interests: ['peaceful spots', 'nightlife'],
        bestTimeOfDay: 'evening',
        locationZone: 'Ernakulam Waterfront',
        description: 'Bustling promenade facing the backwater channels of Kochi with harbor boat cruises and vibrant city skyline views.'
      }
    ],
    hotels: [
      {
        name: 'Brunton Boatyard CGH Earth Heritage Harbor',
        category: 'hotel',
        rating: 4.8,
        reviewCount: 2100,
        sentimentScore: 0.94,
        recentSentimentScore: 0.95,
        recentReviewTrend: 'rising',
        positiveTags: ['Historic Victorian shipyard restoration', 'Balconies overlooking dolphin harbor', 'Colonial era dining'],
        negativeTags: ['High luxury rates', 'Harbor boat horn sounds'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 9500,
        distanceMinutes: 18,
        interests: ['culture', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Fort Kochi Waterfront',
        description: 'Magnificent heritage luxury hotel built on a 19th-century Victorian shipyard with grand teakwood verandas.'
      },
      {
        name: 'Old Harbour Hotel Fort Kochi',
        category: 'hotel',
        rating: 4.7,
        reviewCount: 1850,
        sentimentScore: 0.92,
        recentSentimentScore: 0.93,
        recentReviewTrend: 'stable',
        positiveTags: ['300-year-old Dutch boutique architecture', 'Lush open garden pool', 'Walking distance to fishing nets'],
        negativeTags: ['Limited room inventory', 'Heritage wooden floor creaks'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 6500,
        distanceMinutes: 15,
        interests: ['culture', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Fort Kochi Historic Core',
        description: 'Elegantly preserved 300-year-old heritage boutique hotel boasting lush tropical gardens and authentic Dutch charm.'
      }
    ],
    restaurants: [
      {
        name: 'Kashi Art Cafe Fort Kochi',
        category: 'restaurant',
        rating: 4.6,
        reviewCount: 6500,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'rising',
        positiveTags: ['Warm chocolate cake legend', 'Contemporary art gallery courtyard', 'Relaxed bohemian breakfast vibe'],
        negativeTags: ['Queues during peak brunch hours', 'Limited indoor air conditioning'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 600,
        distanceMinutes: 16,
        interests: ['food', 'culture', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Burgher Street',
        description: 'Cult-favorite courtyard art cafe serving decadent chocolate cake, fresh pressed juices, and artisan organic salads.'
      },
      {
        name: 'Grand Pavilion Kerala Traditional Kitchen',
        category: 'restaurant',
        rating: 4.6,
        reviewCount: 4900,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'stable',
        positiveTags: ['Legendary Syrian beef fry & parotta', 'Clay pot meen curry', 'Consistent culinary heritage'],
        negativeTags: ['Busy family dining rush', 'Reservation recommended on weekends'],
        crowdLevel: 'high',
        priceTier: 'moderate',
        estimatedCostINR: 750,
        distanceMinutes: 4,
        interests: ['food'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'MG Road Ernakulam',
        description: 'A 50-year-old Kochi culinary benchmark famous for authentic Syrian Christian dishes and spiced seafood curries.'
      }
    ]
  },

  // 3. WAYANAD - Mist Hills, Waterfalls, Caves, Wildlife
  {
    city: 'Wayanad',
    places: [
      {
        name: 'Banasura Sagar Dam & Earthen Island Reservoir',
        category: 'place',
        rating: 4.6,
        reviewCount: 13500,
        sentimentScore: 0.89,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'rising',
        positiveTags: ['Largest earthen dam in India', 'Speedboat rides around floating islets', 'Majestic mist hill backdrop'],
        negativeTags: ['Steep walk up from vehicle lot to dam top', 'Long boat ticket wait in summer'],
        crowdLevel: 'medium',
        priceTier: 'budget',
        estimatedCostINR: 350,
        distanceMinutes: 28,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Padinjarathara',
        description: 'India’s largest earth dam creating a surreal reservoir dotted with emerald islands backed by Banasura peaks.'
      },
      {
        name: 'Edakkal Caves & Prehistoric Petroglyphs',
        category: 'place',
        rating: 4.5,
        reviewCount: 11000,
        sentimentScore: 0.87,
        recentSentimentScore: 0.88,
        recentReviewTrend: 'stable',
        positiveTags: ['Neolithic rock etchings dating to 6000 BCE', 'Thrilling hilltop cleft trek', 'Superb valley vista'],
        negativeTags: ['Challenging 1km steep rocky climb', 'Narrow rock passage bottlenecks during rush'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 100,
        distanceMinutes: 35,
        interests: ['culture', 'nature'],
        bestTimeOfDay: 'morning',
        locationZone: 'Ambalavayal',
        description: 'Prehistoric rock shelters split into two natural caverns featuring enigmatic Neolithic drawings and petroglyphs.'
      },
      {
        name: 'Chembra Peak & Heart-Shaped Love Lake Trek',
        category: 'place',
        rating: 4.7,
        reviewCount: 7800,
        sentimentScore: 0.91,
        recentSentimentScore: 0.92,
        recentReviewTrend: 'rising',
        positiveTags: ['Perennial heart-shaped mist lake', 'Highest peak in Wayanad', 'Invigorating grassland trekking trail'],
        negativeTags: ['Strict daily visitor pass quota by forest dept', 'Steep slippery trail during monsoon'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 400,
        distanceMinutes: 42,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Meppadi Hills',
        description: 'Trek to the highest summit in Wayanad featuring a mystical heart-shaped alpine lake nestled halfway to the peak.'
      },
      {
        name: 'Wayanad Wildlife Sanctuary Muthanga Safari',
        category: 'place',
        rating: 4.3,
        reviewCount: 8400,
        sentimentScore: 0.82,
        recentSentimentScore: 0.59,
        recentReviewTrend: 'falling',
        positiveTags: ['Wild elephant herds & spotted deer', 'Dense teak and bamboo forests', 'Official forest jeep safari'],
        negativeTags: ['Wildlife sightings dependent on seasonal luck', 'Bumpy jeeps and long entry queues', 'Safari slots sell out quickly'],
        crowdLevel: 'high',
        priceTier: 'moderate',
        estimatedCostINR: 650,
        distanceMinutes: 30,
        interests: ['nature'],
        bestTimeOfDay: 'morning',
        locationZone: 'Muthanga Forest',
        description: 'Protected bio-reserve contiguous with Bandipur, renowned for free-roaming elephant herds and rich birdlife.'
      }
    ],
    hotels: [
      {
        name: 'Vythiri Resort Rainforest Treehouse Hideaway',
        category: 'hotel',
        rating: 4.8,
        reviewCount: 3100,
        sentimentScore: 0.93,
        recentSentimentScore: 0.95,
        recentReviewTrend: 'rising',
        positiveTags: ['Thatch treehouses 70ft up canopy', 'Natural mountain stream across property', 'Forest suspension bridge'],
        negativeTags: ['Remote forest access road', 'Limited cellular connectivity'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 8800,
        distanceMinutes: 25,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Vythiri Valley',
        description: 'Eco-luxury rainforest sanctuary featuring authentic canopy treehouses and pure mountain springs.'
      },
      {
        name: 'Tranquil Plantation Hideaway & Estate Cottage',
        category: 'hotel',
        rating: 4.6,
        reviewCount: 1400,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'stable',
        positiveTags: ['Coffee & pepper plantation trails', 'Warm family hospitality', 'Serene pool overlooking valley'],
        negativeTags: ['Requires personal cab for sightseeing', 'Fixed dinner menu'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 5500,
        distanceMinutes: 20,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Kuppamudi Estate',
        description: 'A working 400-acre private coffee and vanilla plantation offering nature walks and serene estate cottages.'
      }
    ],
    restaurants: [
      {
        name: "1980's A Nostalgic Restaurant Wayanad",
        category: 'restaurant',
        rating: 4.6,
        reviewCount: 5200,
        sentimentScore: 0.91,
        recentSentimentScore: 0.92,
        recentReviewTrend: 'rising',
        positiveTags: ['Vintage village courtyard ambiance', 'Authentic Malabar chicken biryani & chemmeen roast', 'Plantain leaf thali'],
        negativeTags: ['Expect wait times on weekends', 'Parking fills up fast'],
        crowdLevel: 'high',
        priceTier: 'moderate',
        estimatedCostINR: 500,
        distanceMinutes: 12,
        interests: ['food', 'culture'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Kalpetta Bypass',
        description: 'A nostalgic Kerala village diner serving authentic traditional thalis and Travancore-Malabar culinary gems.'
      },
      {
        name: 'Wilton Restaurant & Grill House',
        category: 'restaurant',
        rating: 4.4,
        reviewCount: 3100,
        sentimentScore: 0.86,
        recentSentimentScore: 0.87,
        recentReviewTrend: 'stable',
        positiveTags: ['Tender Alfaham chicken and kubboos', 'Crispy Kerala porotta', 'Air-conditioned dining lounge'],
        negativeTags: ['Bustling roadside location', 'Moderate wait during dinner peak'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 450,
        distanceMinutes: 18,
        interests: ['food'],
        bestTimeOfDay: 'evening',
        locationZone: 'Sultan Bathery',
        description: 'Popular dining hub famed for charcoal-grilled Arabian chicken, authentic tandoor breads, and Malabar curries.'
      }
    ]
  },

  // 4. THEKKADY (Periyar) - Wildlife, Spice Plantations, Bamboo Rafting, Kalari
  {
    city: 'Thekkady',
    places: [
      {
        name: 'Periyar National Park Lake Boat Safari',
        category: 'place',
        rating: 4.5,
        reviewCount: 16000,
        sentimentScore: 0.87,
        recentSentimentScore: 0.88,
        recentReviewTrend: 'stable',
        positiveTags: ['Submerged tree trunk lake landscapes', 'Elephant herds bathing by water edge', 'Cool forest mountain breeze'],
        negativeTags: ['Boat queues can be tedious', 'Animals remain far from boat path sometimes'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 450,
        distanceMinutes: 10,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Periyar Tiger Reserve',
        description: 'Scenic reservoir boat safari through the core of Periyar Tiger Reserve with frequent elephant and bison sightings.'
      },
      {
        name: 'Kadathanadan Kalari & Kathakali Performing Center',
        category: 'place',
        rating: 4.7,
        reviewCount: 5400,
        sentimentScore: 0.92,
        recentSentimentScore: 0.94,
        recentReviewTrend: 'rising',
        positiveTags: ['Electrifying ancient Kalaripayattu martial arts', 'Fire-jumping and sword battle demonstrations', 'Air-conditioned tiered arena'],
        negativeTags: ['Flash photography prohibited', 'Seating fills rapidly'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 300,
        distanceMinutes: 5,
        interests: ['culture', 'nightlife'],
        bestTimeOfDay: 'evening',
        locationZone: 'Kumily Central',
        description: 'Daily arena showcase of Kalaripayattu, the 3000-year-old mother of martial arts featuring acrobatic weapon battles.'
      },
      {
        name: "Abraham's Organic Spice Garden Heritage Tour",
        category: 'place',
        rating: 4.8,
        reviewCount: 3900,
        sentimentScore: 0.94,
        recentSentimentScore: 0.95,
        recentReviewTrend: 'rising',
        positiveTags: ['Engaging spice cultivation masterclasses', 'Aromatic cardamom, vanilla & pepper vines', 'Ayurvedic plant wisdom'],
        negativeTags: ['Narrow garden trails require walking balance', 'Modest admission fee'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 200,
        distanceMinutes: 12,
        interests: ['nature', 'culture', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Spring Valley Kumily',
        description: 'Guided sensory walking tour through an organic family spice estate explaining cardamom, vanilla, and medicinal flora.'
      },
      {
        name: 'Pandikuzhi Viewpoint & Green Gorge Trail',
        category: 'place',
        rating: 4.4,
        reviewCount: 2800,
        sentimentScore: 0.85,
        recentSentimentScore: 0.86,
        recentReviewTrend: 'stable',
        positiveTags: ['Deep valley panorama between Kerala and Tamil Nadu', 'Whispering pine groves', 'Crisp unpolluted mountain air'],
        negativeTags: ['Unpaved trail approach', 'No commercial tea stalls or restrooms'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 20,
        distanceMinutes: 18,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Border Ridge',
        description: 'Secluded hilltop lookout straddling the Western Ghats border with cascading streams and panoramic valley drops.'
      }
    ],
    hotels: [
      {
        name: 'Spice Village CGH Earth Periyar Forest',
        category: 'hotel',
        rating: 4.8,
        reviewCount: 2600,
        sentimentScore: 0.94,
        recentSentimentScore: 0.95,
        recentReviewTrend: 'rising',
        positiveTags: ['Tribal elephant grass thatched cottages', 'Estate organic spice garden setting', 'Zero plastic eco commitment'],
        negativeTags: ['Premium pricing', 'No television sets in rooms for digital detox'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 8200,
        distanceMinutes: 8,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Kumily Border',
        description: 'Immersive eco-village modeled after indigenous Mannan tribal dwellings set in lush spice gardens.'
      },
      {
        name: 'Poetree Sarovar Portico Forest Ridge',
        category: 'hotel',
        rating: 4.6,
        reviewCount: 1900,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'stable',
        positiveTags: ['Infinity pool gazing into forest canopy', 'Panoramic sunrise mountain views', 'Spacious private balconies'],
        negativeTags: ['Steep access incline road', 'Cab required to town center'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 5200,
        distanceMinutes: 14,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Ottakathalamedu Hill',
        description: 'Hilltop sanctuary overlooking Periyar reserve with an infinity pool perched above misty canopies.'
      }
    ],
    restaurants: [
      {
        name: 'Bamboo Cafe Organic Eatery Thekkady',
        category: 'restaurant',
        rating: 4.5,
        reviewCount: 2100,
        sentimentScore: 0.88,
        recentSentimentScore: 0.90,
        recentReviewTrend: 'rising',
        positiveTags: ['Bamboo-walled eco dining', 'Ginger spice tea & homemade pasta', 'Fresh local river trout curry'],
        negativeTags: ['Cozy but compact dining room', 'Cash only sometimes'],
        crowdLevel: 'low',
        priceTier: 'moderate',
        estimatedCostINR: 550,
        distanceMinutes: 5,
        interests: ['food', 'peaceful spots'],
        bestTimeOfDay: 'evening',
        locationZone: 'Thekkady Bypass Road',
        description: 'Laid-back bamboo-built cafe offering freshly prepared organic dishes, mountain spices, and herbal tea blends.'
      },
      {
        name: 'Dambell Spice Valley Restaurant',
        category: 'restaurant',
        rating: 4.4,
        reviewCount: 1700,
        sentimentScore: 0.86,
        recentSentimentScore: 0.87,
        recentReviewTrend: 'stable',
        positiveTags: ['Flavorsome Travancore duck roast', 'Crispy malabar appam thalis', 'Friendly welcoming hospitality'],
        negativeTags: ['Simple highway decor', 'Limited dessert selections'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 480,
        distanceMinutes: 7,
        interests: ['food'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Kumily Town',
        description: 'Authentic spice kitchen popular for traditional Kerala clay-pot curries and roasted pepper meats.'
      }
    ]
  },

  // 5. KOVALAM - Crescent Beaches, Lighthouse, Ayurveda, Sunset Clifftops
  {
    city: 'Kovalam',
    places: [
      {
        name: 'Lighthouse Beach & Seaside Promenade',
        category: 'place',
        rating: 4.6,
        reviewCount: 17500,
        sentimentScore: 0.89,
        recentSentimentScore: 0.90,
        recentReviewTrend: 'stable',
        positiveTags: ['Iconic 1972 red-striped lighthouse', 'Lively beach cafe promenade', 'Gentle waves suitable for bodyboarding'],
        negativeTags: ['Evening beach bed hawkers', 'Crowded during sunset hours'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 100,
        distanceMinutes: 8,
        interests: ['beaches', 'nightlife', 'food'],
        bestTimeOfDay: 'evening',
        locationZone: 'Southern Crescent',
        description: 'Kovalam’s main crescent beach topped by a towering 35m lighthouse and an unbroken strip of open-air seafood cafes.'
      },
      {
        name: 'Hawah Beach & Sunset Catamaran Point',
        category: 'place',
        rating: 4.5,
        reviewCount: 9200,
        sentimentScore: 0.87,
        recentSentimentScore: 0.88,
        recentReviewTrend: 'rising',
        positiveTags: ['Dramatic black rock promontory', 'Morning catamaran fishermen launches', 'Golden sunset lighting'],
        negativeTags: ['Steep steps down to sand', 'High tides reduce beach width in monsoon'],
        crowdLevel: 'medium',
        priceTier: 'budget',
        estimatedCostINR: 50,
        distanceMinutes: 6,
        interests: ['beaches', 'peaceful spots'],
        bestTimeOfDay: 'evening',
        locationZone: 'Central Crescent',
        description: 'Also known as Eve’s Beach, flanked by rocky headlands where local fishermen launch traditional wooden catamarans.'
      },
      {
        name: 'Samudra Beach & Secluded Coconut Grove',
        category: 'place',
        rating: 4.6,
        reviewCount: 4500,
        sentimentScore: 0.90,
        recentSentimentScore: 0.92,
        recentReviewTrend: 'rising',
        positiveTags: ['Tranquil quiet stretch away from crowds', 'Swaying palm shadows', 'Idyllic for reading and peace'],
        negativeTags: ['Fewer food stalls', 'Rocky seabed sections'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 30,
        distanceMinutes: 12,
        interests: ['beaches', 'peaceful spots', 'nature'],
        bestTimeOfDay: 'morning',
        locationZone: 'Northern Kovalam',
        description: 'The most peaceful of Kovalam’s three crescent bays, protected by natural headlands with unhurried coastal vibes.'
      },
      {
        name: 'Halcyon Castle & Travancore Summer Palace',
        category: 'place',
        rating: 4.4,
        reviewCount: 3800,
        sentimentScore: 0.85,
        recentSentimentScore: 0.86,
        recentReviewTrend: 'stable',
        positiveTags: ['Colonial Travancore royal retreat', 'Expansive manicured clifftop lawns', 'Panoramic Arabian Sea vistas'],
        negativeTags: ['Inner royal chambers restricted', 'Upward hill walk'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 150,
        distanceMinutes: 10,
        interests: ['culture', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Palace Cliff',
        description: 'Constructed in 1932 by M.R. Ry Rama Varma Valiya Koil Thampuran as a royal summer mansion on a cliff overlooking the sea.'
      }
    ],
    hotels: [
      {
        name: 'The Leela Kovalam Cliff Top Resort',
        category: 'hotel',
        rating: 4.8,
        reviewCount: 3800,
        sentimentScore: 0.95,
        recentSentimentScore: 0.96,
        recentReviewTrend: 'rising',
        positiveTags: ['Clifftop infinity pool into the sea horizon', 'Direct private beach cove access', 'World class Ayurvedic wellness center'],
        negativeTags: ['Ultra luxury rates', 'Vast property requires buggy transfers'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 12500,
        distanceMinutes: 7,
        interests: ['beaches', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Clifftop Bluff',
        description: 'Perched on a rocky cliff between two wide beaches, offering majestic Arabian sea views and five-star luxury.'
      },
      {
        name: 'Rockholm at the Lighthouse Beach',
        category: 'hotel',
        rating: 4.6,
        reviewCount: 1400,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'stable',
        positiveTags: ['Uninterrupted ocean view terraces', 'Quiet Ayurvedic yoga retreat', 'Direct steps to lighthouse beach'],
        negativeTags: ['Limited car parking at base', 'Adult-focused quiet atmosphere'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 6800,
        distanceMinutes: 9,
        interests: ['peaceful spots', 'beaches'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Lighthouse Cliff',
        description: 'Art Deco seaside Ayurvedic sanctuary overlooking the lighthouse cove, dedicated to restorative oceanfront living.'
      }
    ],
    restaurants: [
      {
        name: 'Bait Seafood Terrace by Vivanta',
        category: 'restaurant',
        rating: 4.7,
        reviewCount: 2200,
        sentimentScore: 0.93,
        recentSentimentScore: 0.94,
        recentReviewTrend: 'rising',
        positiveTags: ['Candlelight dining right by crashing surf', 'Catch-of-the-day tiger prawns & lobster', 'Signature coconut cocktails'],
        negativeTags: ['High pricing', 'Advance table booking essential on weekends'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 2200,
        distanceMinutes: 10,
        interests: ['food', 'beaches', 'peaceful spots'],
        bestTimeOfDay: 'evening',
        locationZone: 'Kovalam Bayfront',
        description: 'Alfresco fine-dining seafood haven right on the sand serving freshly grilled coastal catch and Kerala spiced delicacies.'
      },
      {
        name: 'Fusion Restaurant Beachfront Shack',
        category: 'restaurant',
        rating: 4.5,
        reviewCount: 3100,
        sentimentScore: 0.88,
        recentSentimentScore: 0.89,
        recentReviewTrend: 'stable',
        positiveTags: ['Generous seafood platters', 'Direct beach promenade people watching', 'Chilled smoothies & craft shakes'],
        negativeTags: ['Open dining gets warm at midday', 'Occasional beach seller chatter'],
        crowdLevel: 'high',
        priceTier: 'moderate',
        estimatedCostINR: 750,
        distanceMinutes: 7,
        interests: ['food', 'beaches', 'nightlife'],
        bestTimeOfDay: 'night',
        locationZone: 'Lighthouse Promenade',
        description: 'Vibrant seafront restaurant famous for calamari fry, sizzlers, Kerala crab curry, and sunset cocktails.'
      }
    ]
  },

  // 6. VARKALA - Red Sandstone Cliffs, Papanasam Holy Beach, Bohemian Cafes
  {
    city: 'Varkala',
    places: [
      {
        name: 'Varkala North Cliff & Red Sandstone Promenade',
        category: 'place',
        rating: 4.7,
        reviewCount: 16000,
        sentimentScore: 0.92,
        recentSentimentScore: 0.93,
        recentReviewTrend: 'rising',
        positiveTags: ['Dramatic 15m red laterite cliff edge', 'Bohemian cafes and live acoustic music', 'Spectacular sunset vantage point'],
        negativeTags: ['Erosion protection work along sections', 'Cliff edge railing requires careful attention'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 50,
        distanceMinutes: 5,
        interests: ['beaches', 'nightlife', 'food'],
        bestTimeOfDay: 'evening',
        locationZone: 'North Cliff Edge',
        description: 'Striking red geological cliffs directly bordering the Arabian Sea, lined with vibrant international cafes and yoga shalas.'
      },
      {
        name: 'Janardhana Swami 2000-Year Ancient Temple',
        category: 'place',
        rating: 4.6,
        reviewCount: 7200,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'stable',
        positiveTags: ['2000-year Vaishnavite sacred heritage', 'Ancient temple banyan tree and pond', 'Intricate Kerala brass lamps'],
        negativeTags: ['Non-Hindus restricted from inner sanctum', 'Strict traditional dress code required'],
        crowdLevel: 'medium',
        priceTier: 'budget',
        estimatedCostINR: 30,
        distanceMinutes: 10,
        interests: ['culture', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Temple Junction',
        description: 'Venerated 2000-year-old pilgrimage shrine dedicated to Lord Vishnu, nicknamed the Benares of the South.'
      },
      {
        name: 'Papanasam Beach & Natural Mineral Springs',
        category: 'place',
        rating: 4.5,
        reviewCount: 11200,
        sentimentScore: 0.88,
        recentSentimentScore: 0.61,
        recentReviewTrend: 'falling',
        positiveTags: ['Sacred cleansing waters', 'Natural mineral spring waterfalls on cliff face', 'Golden sands below cliffs'],
        negativeTags: ['Heavy religious ceremony crowds at dawn', 'Seasonal trash after holiday weekends', 'Steep cliff staircase ascent'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 20,
        distanceMinutes: 8,
        interests: ['beaches', 'culture', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'South Cliff Base',
        description: 'Sacred beach believed to cleanse worldly sins, flanked by natural cliff-face mineral streams and ceremonial ghats.'
      },
      {
        name: 'Kappil Beach & Edava Backwater Estuary',
        category: 'place',
        rating: 4.6,
        reviewCount: 4800,
        sentimentScore: 0.91,
        recentSentimentScore: 0.92,
        recentReviewTrend: 'rising',
        positiveTags: ['Road bisecting lake and Arabian Sea', 'Peaceful uncrowded estuary', 'Country boat and kayak rides'],
        negativeTags: ['No lifeguard on duty', 'Sparse cafe options'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 150,
        distanceMinutes: 16,
        interests: ['nature', 'beaches', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Kappil Estuary',
        description: 'Picturesque convergence point where the serene backwaters of Edava Lake meet the waves of the Arabian Sea.'
      }
    ],
    hotels: [
      {
        name: 'Gateway Varkala by IHCL SeleQtions',
        category: 'hotel',
        rating: 4.7,
        reviewCount: 2200,
        sentimentScore: 0.93,
        recentSentimentScore: 0.94,
        recentReviewTrend: 'rising',
        positiveTags: ['Cliff-edge garden overlooking ocean', 'Sunken pool bar & Ayurvedic treatments', 'Impeccable Taj hospitality'],
        negativeTags: ['Premium pricing tier', 'Short stroll required to reach North Cliff hub'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 7800,
        distanceMinutes: 8,
        interests: ['beaches', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Janardhanapuram Cliff',
        description: 'Luxury cliff-top resort set amidst manicured gardens with ocean-view balconies and sunken swimming pool.'
      },
      {
        name: 'Clafouti Beach Resort Cliff Pavilion',
        category: 'hotel',
        rating: 4.4,
        reviewCount: 1750,
        sentimentScore: 0.86,
        recentSentimentScore: 0.87,
        recentReviewTrend: 'stable',
        positiveTags: ['Right in the heart of North Cliff cafe row', 'Direct cliff sunset panorama', 'Cozy wooden seaside cottages'],
        negativeTags: ['Music from surrounding cliff cafes at night', 'Limited vehicle drop-off at cliff gate'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 3200,
        distanceMinutes: 4,
        interests: ['beaches', 'nightlife'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'North Cliff Walk',
        description: 'Atmospheric wooden cottage resort positioned directly on the North Cliff promenade steps from popular cafes.'
      }
    ],
    restaurants: [
      {
        name: 'Cafe del Mar Varkala Cliff Top',
        category: 'restaurant',
        rating: 4.6,
        reviewCount: 4100,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'rising',
        positiveTags: ['Prime sunset ocean view tables', 'Wood-fired thin crust pizza & seafood pasta', 'Laid-back acoustic sunset sessions'],
        negativeTags: ['Prime cliffside tables fill quickly by 5:30 PM', 'Service slows during sunset rush'],
        crowdLevel: 'high',
        priceTier: 'moderate',
        estimatedCostINR: 650,
        distanceMinutes: 5,
        interests: ['food', 'beaches', 'nightlife'],
        bestTimeOfDay: 'evening',
        locationZone: 'North Cliff Central',
        description: 'Iconic open-deck cliffside cafe celebrated for Italian pizzas, fresh coastal fish, and magical Arabian sunsets.'
      },
      {
        name: 'Darjeeling Cafe & Shanti Lounge Varkala',
        category: 'restaurant',
        rating: 4.5,
        reviewCount: 3400,
        sentimentScore: 0.89,
        recentSentimentScore: 0.90,
        recentReviewTrend: 'stable',
        positiveTags: ['Bohemian floor cushion seating', 'Himalayan thukpa & steamed momos', 'Soulful ambient indie music'],
        negativeTags: ['Very relaxed pace of food delivery', 'No indoor AC'],
        crowdLevel: 'medium',
        priceTier: 'budget',
        estimatedCostINR: 420,
        distanceMinutes: 4,
        interests: ['food', 'nightlife', 'peaceful spots'],
        bestTimeOfDay: 'night',
        locationZone: 'North Cliff Path',
        description: 'Vibrant bohemian hangout featuring Tibetan momos, spiced chai, floor rugs, and late-night world music.'
      }
    ]
  },

  // 7. KUMARAKOM - Vembanad Bird Sanctuary, Backwater Lagoons, Village Life
  {
    city: 'Kumarakom',
    places: [
      {
        name: 'Kumarakom Bird Sanctuary & Mangrove Trail',
        category: 'place',
        rating: 4.5,
        reviewCount: 8900,
        sentimentScore: 0.88,
        recentSentimentScore: 0.89,
        recentReviewTrend: 'stable',
        positiveTags: ['Migratory Siberian storks & darters', 'Shaded wooden watchtower in wetlands', 'Serene dawn birdwatching walks'],
        negativeTags: ['Best bird sightings restricted to Nov-Feb season', 'Mosquito repellent needed on forest path'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 100,
        distanceMinutes: 8,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Vembanad Marshes',
        description: 'Sprawling 14-acre wetland sanctuary on Lake Vembanad sheltering migratory waterbirds, herons, and egrets.'
      },
      {
        name: 'Vembanad Lake Sunset Speedboat Safari',
        category: 'place',
        rating: 4.8,
        reviewCount: 6100,
        sentimentScore: 0.94,
        recentSentimentScore: 0.95,
        recentReviewTrend: 'rising',
        positiveTags: ['India’s longest lake horizon', 'Gentle breeze over open water', 'Silhouetted coconut palms at dusk'],
        negativeTags: ['Water hyacinth patches in shallow channels', 'Higher charter fee for private speedboats'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 1800,
        distanceMinutes: 10,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'evening',
        locationZone: 'Lakefront Marina',
        description: 'Thrilling open-water cruising across the vast expanse of Vembanad Lake catching the golden sunset sheen.'
      },
      {
        name: 'Aymanam Village Heritage & Craft Walk',
        category: 'place',
        rating: 4.6,
        reviewCount: 2900,
        sentimentScore: 0.91,
        recentSentimentScore: 0.92,
        recentReviewTrend: 'rising',
        positiveTags: ['Setting of Arundhati Roy’s The God of Small Things', 'Coir spinning & toddy tapping demo', 'Quiet village canal lanes'],
        negativeTags: ['Requires local guided walk for full context', 'No commercial souvenir stores'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 300,
        distanceMinutes: 15,
        interests: ['culture', 'peaceful spots', 'nature'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Aymanam Rural Belt',
        description: 'Charming model village famed as the backdrop for The God of Small Things, showcasing rural coir spinning and life.'
      },
      {
        name: 'Pathiramanal Island Backwater Sanctuary',
        category: 'place',
        rating: 4.4,
        reviewCount: 3200,
        sentimentScore: 0.86,
        recentSentimentScore: 0.87,
        recentReviewTrend: 'stable',
        positiveTags: ['Uninhabited island paradise reachable by boat', 'Lush botanical butterfly walks', 'Zero vehicular traffic'],
        negativeTags: ['No stalls or drinking water on the island', 'Must coordinate return boat timing'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 400,
        distanceMinutes: 25,
        interests: ['nature', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Mid-Lake Island',
        description: 'An isolated 10-acre green islet surrounded by lake waters, offering sanctuary to over 90 species of local waterbirds.'
      }
    ],
    hotels: [
      {
        name: 'Kumarakom Lake Resort Heritage Luxury Villas',
        category: 'hotel',
        rating: 4.9,
        reviewCount: 4200,
        sentimentScore: 0.96,
        recentSentimentScore: 0.97,
        recentReviewTrend: 'rising',
        positiveTags: ['Heritage 16th-century ancestral homes reconstructed', '250m meandering pool right past villas', 'Prince Charles preferred retreat'],
        negativeTags: ['Premium high-tier rates', 'Advance booking required months ahead'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 13500,
        distanceMinutes: 12,
        interests: ['peaceful spots', 'nature', 'culture'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Vembanad Banks',
        description: 'World-acclaimed luxury resort seamlessly blending restored Kerala architectural manors with a winding pool canal.'
      },
      {
        name: 'Coconut Lagoon CGH Earth Backwater Haven',
        category: 'hotel',
        rating: 4.8,
        reviewCount: 2900,
        sentimentScore: 0.94,
        recentSentimentScore: 0.95,
        recentReviewTrend: 'stable',
        positiveTags: ['Accessible only via scenic boat arrival', 'Preserved Tharavadu wooden mansions', 'Butterfly garden & morning flute concerts'],
        negativeTags: ['Isolated from town vehicular roads', 'High seasonal demand'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 9200,
        distanceMinutes: 16,
        interests: ['culture', 'peaceful spots', 'nature'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Kavanattinkara Basin',
        description: 'Sanctuary of restored wooden homesteads situated directly on the shores of Lake Vembanad reached solely by boat.'
      }
    ],
    restaurants: [
      {
        name: 'Ettukettu Heritage Multi-Cuisine Kumarakom',
        category: 'restaurant',
        rating: 4.7,
        reviewCount: 2400,
        sentimentScore: 0.92,
        recentSentimentScore: 0.93,
        recentReviewTrend: 'stable',
        positiveTags: ['Grand eight-sided heritage royal mansion hall', 'Signature duck mappas and karimeen pollichathu', 'Attentive silver service'],
        negativeTags: ['Upscale pricing', 'Gentle dress code expected'],
        crowdLevel: 'low',
        priceTier: 'luxury',
        estimatedCostINR: 1800,
        distanceMinutes: 11,
        interests: ['food', 'culture'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Resort Waterway',
        description: 'A palatial eight-sided heritage architectural mansion serving refined royal Travancore dishes and local seafood.'
      },
      {
        name: 'Tharavadu Seafood Bar & Lagoon Deck',
        category: 'restaurant',
        rating: 4.5,
        reviewCount: 1800,
        sentimentScore: 0.88,
        recentSentimentScore: 0.89,
        recentReviewTrend: 'rising',
        positiveTags: ['Open wooden deck overlooking peaceful lagoon', 'Spicy pepper prawns with appam', 'Fresh tender coconut desserts'],
        negativeTags: ['Limited table capacity on open deck', 'Service can take 20 minutes for fresh seafood'],
        crowdLevel: 'low',
        priceTier: 'moderate',
        estimatedCostINR: 700,
        distanceMinutes: 9,
        interests: ['food', 'peaceful spots'],
        bestTimeOfDay: 'evening',
        locationZone: 'Canal Bank Kumarakom',
        description: 'Charming waterfront restaurant dishing up authentic backwater catches and fragrant coconut curries in a breezy pavilion.'
      }
    ]
  },

  // 8. THRISSUR (Cultural Capital of Kerala) - Temples, Thrissur Pooram, Kathakali, Royalty
  {
    city: 'Thrissur',
    places: [
      {
        name: 'Vadakkunnathan Temple & Thekkinkadu Maidan',
        category: 'place',
        rating: 4.9,
        reviewCount: 21000,
        sentimentScore: 0.97,
        recentSentimentScore: 0.98,
        recentReviewTrend: 'rising',
        positiveTags: ['UNESCO Award of Excellence heritage', '1000-year-old classic Kerala timber & mural architecture', 'Epicentre of Thrissur Pooram festival'],
        negativeTags: ['Non-Hindus not permitted inside sanctum', 'Traditional dhoti dress code enforced for men'],
        crowdLevel: 'medium',
        priceTier: 'budget',
        estimatedCostINR: 50,
        distanceMinutes: 5,
        interests: ['culture', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Thekkinkadu Heart',
        description: 'Ancient 1000-year-old sprawling temple dedicated to Shiva atop a hillock, celebrated for monumentally carved timber gopurams and rare Mahabharata frescoes.'
      },
      {
        name: 'Shakthan Thampuran Palace & Heritage Museum',
        category: 'place',
        rating: 4.6,
        reviewCount: 8500,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'stable',
        positiveTags: ['Kerala-Dutch royal palace architecture', 'Megalithic gallery & ancient bronze artifacts', 'Serene royal serpent grove (Sarpakavu)'],
        negativeTags: ['No photography inside royal treasury rooms', 'Closed on Mondays'],
        crowdLevel: 'low',
        priceTier: 'budget',
        estimatedCostINR: 60,
        distanceMinutes: 10,
        interests: ['culture', 'peaceful spots'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Chembukkavu Heritage Belt',
        description: 'The royal seat of the Cochin Kingdom’s greatest ruler, Raja Rama Varma, featuring thick laterite walls, Italian marble floors, and weapon galleries.'
      },
      {
        name: 'Kerala Kalamandalam Performing Arts University',
        category: 'place',
        rating: 4.8,
        reviewCount: 6200,
        sentimentScore: 0.95,
        recentSentimentScore: 0.96,
        recentReviewTrend: 'rising',
        positiveTags: ['Legendary gurukula academy of Kathakali & Mohiniyattam', 'Live traditional class training sessions', 'Koothambalam traditional temple theatre'],
        negativeTags: ['30km travel from Thrissur town centre', 'Advance booking required for guided tour'],
        crowdLevel: 'low',
        priceTier: 'moderate',
        estimatedCostINR: 400,
        distanceMinutes: 38,
        interests: ['culture', 'peaceful spots'],
        bestTimeOfDay: 'morning',
        locationZone: 'Cheruthuruthy Riverbank',
        description: 'World-renowned temple of classical Kerala performing arts on the banks of Bharathapuzha river, training masters of Kathakali, Koodiyattam, and percussion.'
      },
      {
        name: 'Paramekkavu Bhagavathy Temple & Pooram Enclave',
        category: 'place',
        rating: 4.7,
        reviewCount: 9400,
        sentimentScore: 0.92,
        recentSentimentScore: 0.93,
        recentReviewTrend: 'rising',
        positiveTags: ['Major ceremonial partner of Thrissur Pooram', 'Spellbinding Panchavadyam percussion ensembles', 'Majestic gilded temple architecture'],
        negativeTags: ['Extreme crowd decibels during festival week', 'Limited street parking nearby'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 30,
        distanceMinutes: 6,
        interests: ['culture'],
        bestTimeOfDay: 'evening',
        locationZone: 'East Fort Circle',
        description: 'Prominent temple directly opposite Vadakkunnathan, famed for leading the grand procession of 15 caparisoned tuskers during Thrissur Pooram.'
      }
    ],
    hotels: [
      {
        name: 'Hyatt Regency Thrissur Cultural Hub',
        category: 'hotel',
        rating: 4.8,
        reviewCount: 2900,
        sentimentScore: 0.94,
        recentSentimentScore: 0.95,
        recentReviewTrend: 'rising',
        positiveTags: ['Modern 5-star comfort near cultural sights', 'Sumptuous Kerala sadhya breakfast buffet', 'Lush swimming pool & spa'],
        negativeTags: ['Premium pricing for city location', 'Suburban drive from central temple round'],
        crowdLevel: 'medium',
        priceTier: 'luxury',
        estimatedCostINR: 6500,
        distanceMinutes: 12,
        interests: ['culture', 'food'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Puzhakkal Lane',
        description: 'Upscale 5-star haven combining international hospitality with traditional Kerala art motifs, located minutes from historic temples.'
      },
      {
        name: 'Joys Palace Heritage Hotel Thrissur',
        category: 'hotel',
        rating: 4.5,
        reviewCount: 2100,
        sentimentScore: 0.88,
        recentSentimentScore: 0.89,
        recentReviewTrend: 'stable',
        positiveTags: ['Walking distance to railway station and Round', 'Grand royal lobby chandelier', 'Well appointed spacious family suites'],
        negativeTags: ['Decor is slightly dated in standard rooms', 'Traffic noise during rush hours'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 3400,
        distanceMinutes: 6,
        interests: ['culture'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'TB Road Central',
        description: 'Popular heritage business and family hotel situated right in central Thrissur with easy access to all cultural and temple landmarks.'
      }
    ],
    restaurants: [
      {
        name: 'Akshaya Pure Veg Brahmin Mess Thrissur',
        category: 'restaurant',
        rating: 4.7,
        reviewCount: 5100,
        sentimentScore: 0.93,
        recentSentimentScore: 0.94,
        recentReviewTrend: 'rising',
        positiveTags: ['Unlimited authentic Kerala plantain leaf sadhya', 'Piping hot ghee roast dosas', 'Crisp unadulterated filter coffee'],
        negativeTags: ['Lunch rush demands quick eating', 'No-frills traditional mess ambiance'],
        crowdLevel: 'high',
        priceTier: 'budget',
        estimatedCostINR: 220,
        distanceMinutes: 5,
        interests: ['food', 'culture'],
        bestTimeOfDay: 'afternoon',
        locationZone: 'Swaraj Round North',
        description: 'Venerated vegetarian culinary institution on Swaraj Round serving gold-standard Kerala sadhya meals and crisp ghee dosas.'
      },
      {
        name: 'Roastown Global Grill & Thrissur Spices',
        category: 'restaurant',
        rating: 4.6,
        reviewCount: 3300,
        sentimentScore: 0.90,
        recentSentimentScore: 0.91,
        recentReviewTrend: 'stable',
        positiveTags: ['Signature Thrissur Syrian duck roast', 'Succulent beef dry fry with malabar parotta', 'Chic contemporary decor'],
        negativeTags: ['Longer wait times on Saturday night', 'Lively music can be loud for quiet talks'],
        crowdLevel: 'medium',
        priceTier: 'moderate',
        estimatedCostINR: 650,
        distanceMinutes: 9,
        interests: ['food', 'culture', 'nightlife'],
        bestTimeOfDay: 'evening',
        locationZone: 'Puzhakkal Road',
        description: 'Celebrated Thrissur grill house marrying slow-roasted Syrian Christian spice classics with contemporary smokehouse grills.'
      }
    ]
  }
];

// Generate structured items matching TravelItem interface
const generatedItems = [];

newCitiesData.forEach(({ city, places, hotels, restaurants }) => {
  const cityCode = city.toLowerCase();

  places.forEach((p, idx) => {
    generatedItems.push({
      id: `${cityCode}-p${idx + 1}`,
      name: p.name,
      destination: city,
      city: city,
      state: 'Kerala',
      category: 'place',
      rating: p.rating,
      reviewCount: p.reviewCount,
      sentimentScore: p.sentimentScore,
      recentSentimentScore: p.recentSentimentScore,
      recentReviewTrend: p.recentReviewTrend,
      positiveTags: p.positiveTags,
      negativeTags: p.negativeTags,
      crowdLevel: p.crowdLevel,
      priceTier: p.priceTier,
      estimatedCostINR: p.estimatedCostINR,
      distanceMinutes: p.distanceMinutes,
      interests: p.interests,
      bestTimeOfDay: p.bestTimeOfDay,
      locationZone: p.locationZone,
      description: p.description
    });
  });

  hotels.forEach((h, idx) => {
    generatedItems.push({
      id: `${cityCode}-h${idx + 1}`,
      name: h.name,
      destination: city,
      city: city,
      state: 'Kerala',
      category: 'hotel',
      rating: h.rating,
      reviewCount: h.reviewCount,
      sentimentScore: h.sentimentScore,
      recentSentimentScore: h.recentSentimentScore,
      recentReviewTrend: h.recentReviewTrend,
      positiveTags: h.positiveTags,
      negativeTags: h.negativeTags,
      crowdLevel: h.crowdLevel,
      priceTier: h.priceTier,
      estimatedCostINR: h.estimatedCostINR,
      distanceMinutes: h.distanceMinutes,
      interests: h.interests,
      bestTimeOfDay: h.bestTimeOfDay,
      locationZone: h.locationZone,
      description: h.description
    });
  });

  restaurants.forEach((r, idx) => {
    generatedItems.push({
      id: `${cityCode}-r${idx + 1}`,
      name: r.name,
      destination: city,
      city: city,
      state: 'Kerala',
      category: 'restaurant',
      rating: r.rating,
      reviewCount: r.reviewCount,
      sentimentScore: r.sentimentScore,
      recentSentimentScore: r.recentSentimentScore,
      recentReviewTrend: r.recentReviewTrend,
      positiveTags: r.positiveTags,
      negativeTags: r.negativeTags,
      crowdLevel: r.crowdLevel,
      priceTier: r.priceTier,
      estimatedCostINR: r.estimatedCostINR,
      distanceMinutes: r.distanceMinutes,
      interests: r.interests,
      bestTimeOfDay: r.bestTimeOfDay,
      locationZone: r.locationZone,
      description: r.description
    });
  });
});

console.log(`Generated ${generatedItems.length} items across ${newCitiesData.length} new cities.`);

// Combine base items (Goa, Munnar, Pondicherry) and generated items
const finalData = [...baseData, ...generatedItems];
console.log(`Total final items in dataset: ${finalData.length}`);

// Write back to destinations.json with pretty indentation
fs.writeFileSync(destinationsPath, JSON.stringify(finalData, null, 2), 'utf-8');
console.log('Successfully wrote updated destinations.json.');
